### ISSUE TITLE
Show post do stream dialog?

### ISSUE THREAD

**Issue by benbachhuber** [prabirshrestha/FacebookSharp#10]
Sorry for my bunch of questions.

How would you show a publish to stream dialog (like most facebook's apss are doing it) ?

Would you use the JavaScript SDK and call fb.ui ? (so that it's not necassery to use extended permissions)

I want to use something like the controls here http://developers.facebook.com/tools/console/

**Comment by prabirshrestha** [comment]
i havent used much of JavasScript SDK but anyways here are some sugestions.

some apps use FBML (Facebook markup langauge) its pertty easy to use. http://developers.facebook.com/docs/reference/fbml/

But here's a note from FB docs
Note: We do not recommend FBML for new developers. If you aren't already using FBML, you should instead implement your application within an iframe, using the JavaScript SDK and social plugins for client-side integration with Facebook services. 

theres no harm in asking questions. please feel free to ask.

**Comment by prabirshrestha** [comment]
closed
