### ISSUE TITLE
 CanvasIframeApplication "Given URL is not allowed by the Application configuration."

### ISSUE THREAD

**Issue by ghost** [prabirshrestha/FacebookSharp#11]
When I use the CanvasIframeApplication sample I receive this message. 
I found on the Internet that I should specify the Website URL but it doesn't change anything. 
It does this when I try to connect with an user who hadn't authorized the application yet. 
I don't know why it doesn't work, as it worked pretty fine before.

Thanks for your help.

**Comment by prabirshrestha** [comment]
you have to register an app in facebook, and change the appropriate values in web.config

make sure you url ends with / in the facebook application settings in facebook.com

like

http://localhost/

http://samplefacebookapp.com/

please feel free to ask incase it doesnt solve.

**Comment by ghost** [comment]
I have already done everything you said. 
I have also:
JSON Encoding Empty Arrays: Enabled
Canvas Session Parameter : Enabled
OAuth 2.0 for Canvas (beta) : Enabled

**Comment by prabirshrestha** [comment]
i think this might help you. http://forum.developers.facebook.net/viewtopic.php?pid=262754

"yout might need to add to site URL to the app settings Settings->Web Site->Site URL."

for some it solved, others didnt. anyways you can try it out. if not I will recheck the CanvasIFrameApplication sample when im at home.

**Comment by ghost** [comment]
Thanks for your research but it doesn't work (already tried as specified in my first message ;))  I wonder if it's not a new bug on facebook, because it worked fine with your code, and now it doesn't work. I found this bug, which is only 2 days old:
http://bugs.developers.facebook.net/show_bug.cgi?id=12463

**Comment by prabirshrestha** [comment]
if it was working properly and all of a sudden it stopped workin, its most likely facebook changed some stuffs.

2days back i had faced with a similar change in fb api, http://forum.developers.facebook.net/viewtopic.php?id=74494

you can find more information at fb platform live status website

http://developers.facebook.com/live_status

or can subscribe to the rss feeds of live status at http://www.facebook.com/feeds/api_messages.php

you can also subscribe to email notifications.

**Comment by ghost** [comment]
Thanks for the informations and for your time :)
The bug was indeed from facebook, and has been fixed by one of their developper. 
( http://bugs.developers.facebook.net/show_bug.cgi?id=12463 ).

**Comment by prabirshrestha** [comment]
great that its fixed. 

closing the issue.
