### ISSUE TITLE
Outdated code in FacebookSampleASPNETApp.zip

### ISSUE THREAD

**Issue by altodorov** [prabirshrestha/FacebookSharp#13]
I have a FB iframe app which attempts to post news to my wall. I downloaded the code in FacebookSampleASPNETApp.zip, but I guess it's old.

First, the API Key and the Application Secret of the FB app aren't used nowhere.

When I try to log, I first see a dialog with:
Invalid Argument
Given URL is not allowed by the Application configuration.

Then another with:
An error occurred with [app-name-here]. Please try again later.
API Error Code: 100
API Error Description: Invalid parameter
Error Message: next is not owned by the application.

When I call my app from my FB page, I'm getting:
The remote server returned an error: (403) Forbidden.
Source Error: 
Line 44:                 Dictionary<string, string> postArgs = new Dictionary<string, string>();
Line 45:                 postArgs["message"] = txtMessage.Text.Trim();
Line 46:                 api.Post("/" + fbConnect.UserID + "/feed", postArgs);
Line 47: 
Line 48:                 lblMesageResult.Text = "Posted a message to " + facebookName + "'s feed";
Source File: ...\FacebookSampleASPNETApp\Default.aspx.cs    Line: 46 

Something is missing in the request sent to FB, but I don't know what since everything is handled by the fb:login-button; the OAuth process is hidden.

Is there a workaround? I see the other download, prabirshrestha-FacebookSharp-13b184e.tar.gz is more complete, but is it more up to date?

**Comment by prabirshrestha** [comment]
there is no file called FacebookSampleASPNETApp.zip. 

are you sure you are downloading the latest artifacts from http://teamcity.codebetter.com/viewType.html?buildTypeId=bt262&tab=buildTypeStatusDiv

latest version download as of this writing is FacebookSharp-0.1.0.102--bin.zip4 

if you want the source code, you will have to download prabirshrestha-FacebookSharp-13b184e.tar.gz 

at the moment there are 5 samples:
1. FacebookSharp.Samples.CanvasIFrameApplication
2. FacebookSharp.Samples.Mvc
3. FacebookSharp.Samples.Silverlight
4. FacebookSharp.Samples.WebApplication
5. FacebookSharp.Samples.WinForms

which one did you try out?

if you are using web application, did you change the the appropriate settings in appSettings?

<add key="FacebookSharp.AppKey" value="AppKey"/>
<add key="FacebookSharp.AppSecret" value="AppSecret"/>
<add key="FacebookSharp.PostAuthorizeUrl" value="PostAuthorizeUrl"/>

as pointed out in README, did you enable Canvas Session Parameter and OAuth 2.0 for Canvas (beta) in Advanced Tab in application settings?

are you sure that your canvas url ends with / in facebook.com/developers settings?
http://localhost:1490/

and my samples doesnt use fbml at all. the one you mentioned. fb:login-button

could you clarify it more.

**Comment by altodorov** [comment]
Sorry! I must have downloaded code from different github location, like http://github.com/facebook/csharp-sdk. I actually found the link to your implementation there after trying the one that didn't work. Please feel free to close this ticket and accept my appologies.

I tried your code (with the webb app sample) and it worked as expected. I only had to modify the specific permissions I need and of course replace app settings with mine.

If you have a couple of minutes i'd really appreciate your feedback on the following:

I'm trying to automate a simple scenario with a single user who posts feeds to his own wall with a sandboxed app. I want to get the access token once, then reuse in subsequent requests (posts). Do you know if FB expire access tokens? I asked in a FB forum but didn't get a reply so far. 

Thanks.

**Comment by prabirshrestha** [comment]
FB access token does expire.
but u can tell it not to expire by passing offline_access.
its called extended permission.
you can read more about it in facebook documenation. http://developers.facebook.com/docs/authentication/permissions

incase ur using FacebookSharp, u can easily do by fbSettings.DefaultApplicationPermissions = new[] { "publish_stream","offline_access" } };

i highly recommend u to read http://github.com/prabirshrestha/FacebookSharp/blob/master/README.md

incase you have any questions about Facebook or FacebookSharp in particular please feel free to ask.

After all opensource softwares/libraries has nothing to lose.

**Comment by prabirshrestha** [comment]
closed
