### ISSUE TITLE
(#200) The user hasn't authorized the application to perform this action

### ISSUE THREAD

**Issue by witiokz** [prabirshrestha/FacebookSharp#16]
The same problem, as in all other plugins. 

(#200) The user hasn't authorized the application to perform this action

**Comment by prabirshrestha** [comment]
which resource are you trying to access?
/me ? or /picture or something else
can you specify it. ( i will try in my machine)

and do you have the appropriate extended permissions? you can see the list of permissions here http://developers.facebook.com/docs/authentication/permissions

**Comment by witiokz** [comment]
I am very very sorry.  I am new in facebook development and information in the web is very unclear. The problem was in permissions, but it would be great if you post that data in documentation. Thanks

**Comment by prabirshrestha** [comment]
actually all this things are already commented in readme.md

https://github.com/prabirshrestha/FacebookSharp/blob/master/README.md

can you read all of it.

to add extended permissions you can use this when authorizing the user.
fbSettings.DefaultApplicationPermissions = new[] { "publish_stream","create_event" } };

what type of app are you creating?
asp.net mvc,webforms, silverlight, windows phone 7, 
canvas iframe application.

please feel free to ask any questions.

**Comment by witiokz** [comment]
I am using webforms, and only want to post an information to the wall :).

**Comment by witiokz** [comment]
could you share working example of posting data to the wall, thanks

**Comment by prabirshrestha** [comment]
https://github.com/prabirshrestha/FacebookSharp/blob/master/src/Samples/FacebookSharp.Samples.WebApplication/FacebookContext.cs#L28

add settings.DefaultApplicationPermissions = new[] { "publish_stream" } };

**Comment by prabirshrestha** [comment]
i updated the sample webforms app for posting on wall. and also retrieving the posted message.
could you download the latest source code and try again.

https://github.com/prabirshrestha/FacebookSharp/commit/43626ef46d5465effdefbc0832222653d4695c29

**Comment by witiokz** [comment]
all works, thanks.

**Comment by prabirshrestha** [comment]
glad to hear that it is working.
im closing this issue.
