### ISSUE TITLE
problem at post authorize url

### ISSUE THREAD

**Issue by arnab74** [prabirshrestha/FacebookSharp#23]
Prabir hi,
I'm trying to use your mvc sample, I have added the app id and secret key.
But when I try to link the facebook account,it threw an error at:
public long GetFacebookExpiresIn(string membershipUsername)
        {
            throw notimplemented exception;
        }

So I added "return 32767;" in its place and I was able to log in at facebook but then at postauthorizeurl it is throwing another error:

Exception Details: FacebookSharp.OAuthException: Error validating client secret.

Source Error: 

Line 35:                 var fbException = (FacebookException)result;
Line 36:                 if (fbException != null)
Line 37:                     throw fbException;
Line 38: 
Line 39:                 // the result comes like the querystring

I have rechecked my secret key and it is correct.

Could you please check:

Thanks and regards
Arnab

**Comment by arnab74** [comment]
Sorry, my fault, there was a space, got it working........

**Comment by prabirshrestha** [comment]
closed.
